/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-surface": "#e2e2e2",
        "error-container": "#93000a",
        "inverse-primary": "#775a19",
        "tertiary-container": "#a7a5a5",
        "on-primary-fixed-variant": "#5d4201",
        "on-tertiary-fixed": "#1b1c1c",
        "secondary-fixed-dim": "#c8c6c5",
        "inverse-on-surface": "#2f3131",
        "on-primary-fixed": "#261900",
        "secondary-fixed": "#e5e2e1",
        "on-secondary-container": "#bab8b7",
        "secondary": "#c8c6c5",
        "primary-fixed": "#ffdea5",
        "primary-container": "#c5a059",
        "on-tertiary": "#303030",
        "surface-tint": "#e9c176",
        "on-primary-container": "#4e3700",
        "outline-variant": "#4e4639",
        "surface-container": "#1e2020",
        "on-secondary-fixed": "#1c1b1b",
        "surface-bright": "#38393a",
        "surface-container-highest": "#333535",
        "on-surface-variant": "#d1c5b4",
        "secondary-container": "#4a4949",
        "tertiary-fixed-dim": "#c8c6c5",
        "error": "#ffb4ab",
        "on-secondary-fixed-variant": "#474646",
        "primary": "#e9c176",
        "on-background": "#e2e2e2",
        "tertiary-fixed": "#e4e2e1",
        "on-error": "#690005",
        "surface-container-high": "#282a2b",
        "surface-variant": "#333535",
        "primary-fixed-dim": "#e9c176",
        "on-tertiary-fixed-variant": "#474746",
        "outline": "#9a8f80",
        "on-error-container": "#ffdad6",
        "background": "#121414",
        "tertiary": "#c8c6c5",
        "on-secondary": "#313030",
        "surface-container-lowest": "#0c0f0f",
        "on-tertiary-container": "#3b3b3b",
        "inverse-surface": "#e2e2e2",
        "on-primary": "#412d00",
        "surface-container-low": "#1a1c1c",
        "surface-dim": "#121414",
        "surface": "#121414"
      },
      spacing: {
        "md": "24px",
        "sm": "12px",
        "base": "8px",
        "gutter": "24px",
        "lg": "48px",
        "xs": "4px",
        "xl": "80px",
        "container-max": "1280px"
      },
      fontFamily: {
        "headline-md": ["EB Garamond", "serif"],
        "display-lg-mobile": ["EB Garamond", "serif"],
        "headline-sm": ["EB Garamond", "serif"],
        "display-lg": ["EB Garamond", "serif"],
        "label-caps": ["Manrope", "sans-serif"],
        "button": ["Manrope", "sans-serif"],
        "body-lg": ["Manrope", "sans-serif"],
        "body-md": ["Manrope", "sans-serif"]
      }
    },
  },
  plugins: [],
}
